### ISSUE TITLE
Linda: Chat 

### ISSUE THREAD

**Issue by avabrooks** [evagravin/p4-kangaroos#16]
- [x] Work on chat server
 - [x] Review the presentation of Creating a Chat Interface
     - [x] Research on how to connect the chatting functionality with the interface
Completion date: 06/01

**Comment by devamshri** [comment]
You have a very interesting ticket which is good. I think you can be more specific with the processes that you take toward completing this task as it will help you be more on top of the project.

**Comment by sriyachilla** [comment]
I like that you also had the research aspect in your tickets because it is a necessary part of building the chat function. I think you could also look at Mr. Hennessey's previous Tech Talks on creating a chat feature. You are specific in your tickets. 9/10

**Comment by 4disease** [comment]
Good ticket with nice detail! It could be useful to have some links to research or go more into detail with how you will complete each check.

**Comment by evagravin** [comment]
This is a really good ticket. Maybe you can go more into depth about the steps you will take. :)
