### ISSUE TITLE
Ava: School Signup to Work With Crossover

### ISSUE THREAD

**Issue by avabrooks** [evagravin/p4-kangaroos#19]
- [x] Change Signup page to ask for school
- [x] Display school on Profile Page
 - [x] Create a 'groups' page to show all members in del Norte group 
   - [x] grab usernames from db and filter through to only display usernames in that certain group

**Comment by evagravin** [comment]
Incorporating the "school" part of our website will be a great addition. I think changing the signup page to ask for the school is the first step in reaching this goal and showing all the members in the group on the website will be the last step. Is there a lot of backend involved? It seems like how you are going to filter by the usernames that are in each group will be very effective!

**Comment by avabrooks** [comment]
`


from flask import Blueprint, render_templatefrom TheSmack.users.user import get_users

groups_bp = Blueprint('groups', __name__,                          template_folder='templates',                          static_folder='static')
@groups_bp.route('/')def groups():    return render_template("/groups/groups.html")

@groups_bp.route('/delnorte')def delnorte_groups():    users=get_users("Del Norte High School")    return render_template("/groups/delNorte.html", users=users)

@groups_bp.route('/mtCarmel', methods=['GET' 'POST'])def mtCarmel_groups():    return render_template("/groups/mtCarmel.html")

`

**Comment by avabrooks** [comment]
- New input type on sign up form [here](https://github.com/evagravin/p4-kangaroos/blob/main/templates/users/signup.html#L17-L24)
- Passed through variable school on the route [here](https://github.com/evagravin/p4-kangaroos/blob/main/TheSmack/users/app.py#L72) which is called on the front end [here](https://github.com/evagravin/p4-kangaroos/blob/main/templates/users/profile.html#L8) and displayed on user's profile
- Created 'groups' page
  - Blueprint [here](https://github.com/evagravin/p4-kangaroos/blob/main/TheSmack/groups/app.py#L1-L17)
  - Groups menu page [here](https://github.com/evagravin/p4-kangaroos/blob/main/templates/groups/groups.html)
  - Del Norte group page [here](https://github.com/evagravin/p4-kangaroos/blob/main/templates/groups/delNorte.html)
    - Passed variables from [backend](https://github.com/evagravin/p4-kangaroos/blob/main/TheSmack/groups/app.py#L17) are called [here](https://github.com/evagravin/p4-kangaroos/blob/main/templates/groups/delNorte.html#L27-L28) and displayed on table to show all users in 'Del Norte' Group
      - Backend work of query through db [here](https://github.com/evagravin/p4-kangaroos/blob/main/TheSmack/users/user.py#L41-L42)
