### ISSUE TITLE
Ava: Home Page + Groups

### ISSUE THREAD

**Issue by avabrooks** [evagravin/p4-kangaroos#25]
- [x] Home page
   - [x] Implement "most recent Smack"
     - [x] Connect to db(most likely Guest table)
     - [x] Create function that refreshes over certain intervals
     - [x] Use jinja to display most recent Smack
   - [x] Fix formatting so menu drops below nav bar option
- [x] Groups page(guest interface)
  - [x] Finish creating group pages for each PUSD high school 
  - [x] Display users in each group
  - [x] Potentially start working on logged in user interface for groups(likely DN only)

**Comment by evagravin** [comment]
I was trying to figure this out as well... this is a good ticket because it is challenging but should be able to be fixed as well!

**Comment by risaiwazaki** [comment]
Nice ticket overall! It is very detailed and I like how you focus both on the group page as well as the home page. I also like the idea of starting with just DN for the logged in user interface to see what we are working with. Once that is done, hopefully we could do potentially other schools as well!

**Comment by lindalonglong** [comment]
Your ticket is really organized and thorough! I like how you list these sub bullet points to show your coding plan, each of them is goal-oriented and specific. I wonder how the guest interface would look like, it is an interesting functionality!
